name: 🚔 CI
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      GO_VERSION:
        description: "Go version to use"
        required: false
        default: "1.24"
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  auto_labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "useless-solutions/.github"
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yml

  detect_language:
    runs-on: ubuntu-latest
    outputs:
      is_go: ${{ steps.detect.outputs.is_go }}
    steps:
      - uses: actions/checkout@v4
      - name: Detect repo language
        id: detect
        run: echo "is_go=$( [ -f go.mod ] && echo true || echo false )" >> "$GITHUB_OUTPUT"

  go_lint:
    needs: detect_language
    if: ${{ needs.detect_language.outputs.is_go == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.GO_VERSION }}
      - name: lint
        uses: golangci/golangci-lint-action@v6.5.0
